# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tpu_raiden.rpc import coordination_pb2 as tpu__raiden_dot_rpc_dot_coordination__pb2


class CoordinationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransferMetadata = channel.unary_unary(
                '/tpu_raiden.rpc.CoordinationService/GetTransferMetadata',
                request_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataRequest.SerializeToString,
                response_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/tpu_raiden.rpc.CoordinationService/Shutdown',
                request_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.CollectReplicaInfo = channel.unary_unary(
                '/tpu_raiden.rpc.CoordinationService/CollectReplicaInfo',
                request_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoRequest.SerializeToString,
                response_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoResponse.FromString,
                _registered_method=True)


class CoordinationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTransferMetadata(self, request, context):
        """Queries peer server and returns metadata (port, block_ids, host_ip).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Signals peer CoordinationServer to shut down and exit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectReplicaInfo(self, request, context):
        """Collects the metadata info across all replicas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransferMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransferMetadata,
                    request_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataRequest.FromString,
                    response_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownRequest.FromString,
                    response_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownResponse.SerializeToString,
            ),
            'CollectReplicaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectReplicaInfo,
                    request_deserializer=tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoRequest.FromString,
                    response_serializer=tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tpu_raiden.rpc.CoordinationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tpu_raiden.rpc.CoordinationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTransferMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu_raiden.rpc.CoordinationService/GetTransferMetadata',
            tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataRequest.SerializeToString,
            tpu__raiden_dot_rpc_dot_coordination__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu_raiden.rpc.CoordinationService/Shutdown',
            tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownRequest.SerializeToString,
            tpu__raiden_dot_rpc_dot_coordination__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectReplicaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu_raiden.rpc.CoordinationService/CollectReplicaInfo',
            tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoRequest.SerializeToString,
            tpu__raiden_dot_rpc_dot_coordination__pb2.CollectReplicaInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
