# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpu_raiden/rpc/coordination.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tpu_raiden/rpc/coordination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!tpu_raiden/rpc/coordination.proto\x12\x0etpu_raiden.rpc\"$\n\x0fMetadataRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"6\n\x12\x45ndpointDescriptor\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x0e\n\x06shards\x18\x02 \x03(\x03\"\x8c\x01\n\x10MetadataResponse\x12\x35\n\tendpoints\x18\x01 \x03(\x0b\x32\".tpu_raiden.rpc.EndpointDescriptor\x12\x15\n\rtransfer_uuid\x18\x02 \x01(\x04\x12\x17\n\x0ftransfer_req_id\x18\x03 \x01(\t\x12\x11\n\tblock_ids\x18\x04 \x03(\x05\"$\n\x0fShutdownRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"#\n\x10ShutdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"T\n\x19\x43ollectReplicaInfoRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x65xpected_count\x18\x02 \x01(\x05\x12\x0c\n\x04info\x18\x03 \x03(\x05\"O\n\x1a\x43ollectReplicaInfoResponse\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .tpu_raiden.rpc.ReplicaInfoEntry\"3\n\x10ReplicaInfoEntry\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x12\x0c\n\x04info\x18\x02 \x03(\x05\x32\xab\x02\n\x13\x43oordinationService\x12X\n\x13GetTransferMetadata\x12\x1f.tpu_raiden.rpc.MetadataRequest\x1a .tpu_raiden.rpc.MetadataResponse\x12M\n\x08Shutdown\x12\x1f.tpu_raiden.rpc.ShutdownRequest\x1a .tpu_raiden.rpc.ShutdownResponse\x12k\n\x12\x43ollectReplicaInfo\x12).tpu_raiden.rpc.CollectReplicaInfoRequest\x1a*.tpu_raiden.rpc.CollectReplicaInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpu_raiden.rpc.coordination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATAREQUEST']._serialized_start=53
  _globals['_METADATAREQUEST']._serialized_end=89
  _globals['_ENDPOINTDESCRIPTOR']._serialized_start=91
  _globals['_ENDPOINTDESCRIPTOR']._serialized_end=145
  _globals['_METADATARESPONSE']._serialized_start=148
  _globals['_METADATARESPONSE']._serialized_end=288
  _globals['_SHUTDOWNREQUEST']._serialized_start=290
  _globals['_SHUTDOWNREQUEST']._serialized_end=326
  _globals['_SHUTDOWNRESPONSE']._serialized_start=328
  _globals['_SHUTDOWNRESPONSE']._serialized_end=363
  _globals['_COLLECTREPLICAINFOREQUEST']._serialized_start=365
  _globals['_COLLECTREPLICAINFOREQUEST']._serialized_end=449
  _globals['_COLLECTREPLICAINFORESPONSE']._serialized_start=451
  _globals['_COLLECTREPLICAINFORESPONSE']._serialized_end=530
  _globals['_REPLICAINFOENTRY']._serialized_start=532
  _globals['_REPLICAINFOENTRY']._serialized_end=583
  _globals['_COORDINATIONSERVICE']._serialized_start=586
  _globals['_COORDINATIONSERVICE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
